### ISSUE TITLE
unable to run demos on ubuntu

### ISSUE THREAD

**Issue by Ali-Alzyoud** [dalihub/nui-demo#32]
with build example with latest  dalihub libs I get following error:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'SWIGStringHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libdali-csharp-binder.so': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Tizen.NUI.NDalicPINVOKE.SWIGStringHelper.SWIGRegisterStringCallback_NDalic(SWIGStringDelegate stringDelegate)
   at Tizen.NUI.NDalicPINVOKE.SWIGStringHelper..cctor() in /home/ali/TizenFX/src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs:line 213
   --- End of inner exception stack trace ---
   at Tizen.NUI.NDalicPINVOKE.SWIGStringHelper.RegistCallback() in /home/ali/TizenFX/src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs:line 216
   at Tizen.NUI.NUICoreBackend.Run(String[] args) in /home/ali/TizenFX/src/Tizen.NUI/src/internal/NUICoreBackend.cs:line 138
   at Tizen.Applications.CoreApplication.Run(String[] args) in /home/ali/TizenFX/src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs:line 125
   at Tizen.NUI.NUIApplication.Run(String[] args) in /home/ali/TizenFX/src/Tizen.NUI/src/public/NUIApplication.cs:line 242
   at HelloWorldExample.Main(String[] args) in /home/ali/nui-demo/hello-world/HelloWorld.cs:line 84
```

**Note 'libdali-csharp-binder.so' is not founded in my system, it is called 'libdali2-csharp-binder.so':**

**Comment by huiyueun** [comment]
Please change lib name "libdali-csharp-binder.so" to "libdali2-csharp-binder2.so" in NDalicPINVOKE.cs file. We will use it temporarily and apply it later.
